### ISSUE TITLE
New Update broke the mod.

### ISSUE THREAD

**Issue by bytorphoto** [kevinwilso05/tillvalhalla#56]
The latest Valheim update 2.16.9 n-5 has rendered the mod unusable. It either doesn't let me log in to my servers, or hangs, or just does nothing.

**Comment by bytorphoto** [comment]
Getting this every time. Please fix?

`[Info   :   BepInEx] Loading [TillValhalla 2.4.2]
[Message:TillValhalla.TillValhalla] Loaded Game Configuration
[Message:TillValhalla.TillValhalla] Configuration file successfully loaded
[Info   :TillValhalla.TillValhalla] ModStub has landed
[Message:TillValhalla.TillValhalla] Loaded Game Configuration
[Message:TillValhalla.TillValhalla] Loaded Beehive Configuration
[Message:TillValhalla.TillValhalla] Loaded ItemDrop Configuration
[Message:TillValhalla.TillValhalla] Loaded Inventory Configuration
[Message:TillValhalla.TillValhalla] Loaded Ship Configuration
[Message:TillValhalla.TillValhalla] Loaded CraftingStation Configuration
[Message:TillValhalla.TillValhalla] Loaded Gather Configuration
[Message:TillValhalla.TillValhalla] Loaded Player Configuration
[Message:TillValhalla.TillValhalla] Loaded Plant Configuration
[Message:TillValhalla.TillValhalla] Loaded Container Configuration
[Message:TillValhalla.TillValhalla] Loaded Smelter Configuration
[Message:TillValhalla.TillValhalla] Loaded Sap Collection Configuration
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type SEMan and name AddStatusEffect and parameters (string, bool, int, float)
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static bool TillValhalla.GameClasses.Waterproof+SEMan_RemoveWetFromRain_Patch::Prefix(SEMan __instance, string name)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
TillValhalla.TillValhalla.Awake () (at <74437aaba455411ea487a8d2d1dda3d0>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.UI.Image:OnCanvasHierarchyChanged()
`

**Comment by kevinwilso05** [comment]
Issue was fixed in previous update.
