### ISSUE TITLE
Newest Update conflicting with Jewelcrafting mod

### ISSUE THREAD

**Issue by falkon311** [kevinwilso05/tillvalhalla#59]
Heyahs,

With your new version installed and a fresh config file, when I go to open the mods crafting station, the "Gemcutters Table", nothing happens in the game but Bepinex shows the following:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
CraftingStation.CheckUsable (Player player, System.Boolean showMessage) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
CraftingStation.Interact (Humanoid user, System.Boolean repeat, System.Boolean alt) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
Player.Interact (UnityEngine.GameObject go, System.Boolean hold, System.Boolean alt) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

With your mod uninstalled- no issues.
With the previous version of your mod installed- no issues.

Is it the new thing, the hotbar switcher? Not even really sure what that does. Hitting ` just made my hotbar disappear :D

Happy to use the previous version but also happy to do any testing if that'd be helpful. Just let me know!

Mod mentioned- https://thunderstore.io/c/valheim/p/Smoothbrain/Jewelcrafting/

**Comment by falkon311** [comment]
Figured I'd throw this in here as well as it contains your mods name. Something to do with Jotunn during initial load.

[Warning:Jotunn.EventExtensions] Exception thrown at event InvokeOnVanillaObjectsAvailable in TillValhalla.ModifyVanillaItems:
System.IO.FileNotFoundException: Could not load file or assembly 'MonoMod.Backports, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'MonoMod.Backports, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'
  at Jotunn.EventExtensions.SafeInvoke (System.Action events) [0x00018] in D:\Projects\Jotunn\JotunnLib\Extensions\EventExtensions.cs:26
[Info   :Jotunn.Managers.ItemManager] Adding 69 custom items to the ObjectDB

**Comment by kevinwilso05** [comment]
Thank you, I'll take a look, will likely revert the changes and do some more testing.

**Comment by falkon311** [comment]
Cool tools man. I asked around Odin Discord and I received some feedback regarding the Jotunn warning:

"means they compiled against the latest Harmony version, let the TillValhalla author know they need to compile against the one that is shipped with BepInEx"

Also, not sure if this is something you could resolve, but, when using https://thunderstore.io/c/valheim/p/Azumatt/AAA_Crafting/ , crafting from containers is still possible but the crafting stations no longer show the amount of mats you have in storage, only on your person. You can still craft said items if you have enough mats in storage, it's just impossible to tell without checking storage manually. Azu has a "craft from containers" mod that I'm assuming is compatible, might have something in there to help. I guess I could use Azu's mod and disable your crafting from 
containers section but I'm really trying to keep the # of mods running to a minimum lol.

Seriously tho, love this mod, does so much in one menu, a must have! Appreciate all your time/effort.

**Comment by kevinwilso05** [comment]
I just pushed a new update and tested with the gem crafting mod and got no errors when tested the use case that you provided. Let me know if you have any issues. V2.4.8

**Comment by falkon311** [comment]
Works like a charm! I see the info for the Jotunn warning proved useful too as I don't see it anymore!

Questions: What does the "Disable Build Restrictions" option do? I see the description of "restrictions on spawn"... when we spawn into the game initially or any time we log in? Or is it something else altogether? 

Also, what is this hotkey, rows to switch functionality? Actually, now that I've typed it out... forget I asked lol. The issue is that sorting brings everything away from that second row... unless I favorite them ahhhhh. Slowly figuring this all out lol.

**Comment by kevinwilso05** [comment]
The disable build restrictions should allow for building in restricted areas, like spawn where you would previously have the message that a "Mystical Force Prevents" you from building here. And yes, that's how the hot bar switch works :) I was going to mention that earlier. Feel free to shoot me a message on discord if you have any other questions - kevinwilso00 .
